[package]
name = "virtualbutfake/simpoll"
description = "A bidirectional long-polling library designed for use with Roblox."
version = "0.2.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@2.0.1"